# Generated by Django 5.2 on 2025-05-08 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0001_initial'),
        ('quizzes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizz',
            name='questions',
            field=models.ManyToManyField(related_name='quizzes', to='questions.question'),
        ),
    ]
